apiVersion: k8s.checklyhq.com/v1alpha1
kind: ApiCheck
metadata:
  annotations:
  finalizers:
  - k8s.checklyhq.com/finalizer
  name: rpc-test
spec:
  endpoint: https://foo.com
  success: "200"
  group: test
